enter:
  id:
    android: "medianet.luckia:id/login_toolbar"
    ios: ""

register:
  id:
    android: "medianet.luckia:id/register_toolbar"
    ios: ""

navigation-menu:
  class:
    android: "android.widget.ImageButton"
    ios: ""
