enter:
  id:
    android: "medianet.luckia:id/login_toolbar"
    ios: ""

register:
  id:
    android: "medianet.luckia:id/register_toolbar"
    ios: ""

navigation-menu:
  class:
    android: "android.widget.ImageButton"
    ios: ""

top_limit:
  xpath:
    android: "//*[@resource-id='medianet.luckia:id/webView_frag']"
    ios: ""

bottom_limit:
  xpath:
    android: "//*[@resource-id='medianet.luckia:id/locales_icon']"
    ios: ""
