user:
  id:
    android: "medianet.luckia:id/edit_user"
    ios: ""

pass:
  id:
    android: "medianet.luckia:id/edit_password"
    ios: ""

sign_in:
  id:
    android: "medianet.luckia:id/button_login"
    ios: ""

back:
  id:
    android: "medianet.luckia:id/continue_unlogged"
    ios: ""

forgotten_pass:
  id:
    android: "medianet.luckia:id/continue_unlogged" 
    ios: ""
