deposit:
  id:
    android: "medianet.luckia:id/button_depositar"
    ios: ""

account_name:
  id:
    android : "medianet.luckia:id/account_name"
    ios: ""

account_balance:
  id:
    android: "medianet.luckia:id/account_balance"
    ios: ""

profile_menu:
  id:
    android: "medianet.luckia:id/profile_drawer_icon"
    ios: ""

top_limit:
  xpath:
    android: "//*[@resource-id='medianet.luckia:id/webView_frag']"
    ios: ""

bottom_limit:
  xpath:
    android: "//*[@resource-id='medianet.luckia:id/locales_icon']"
    ios: ""
